name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-gh-pages-deploy
      uses: crazy-max/ghaction-github-pages@master
      with:
        target_branch: gh-pages
        build_dir: docs/.vuepress/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

